### PR TITLE
Added individual configuration feature

### PR DESCRIPTION
**Pull request by mrwogu**
With this feature we can use multiple file managers with different options for each individually.

++ Small bugfix with search bar.
++ Added new configuration option which allows enable or disable language selector.

### CODE REVIEW

**Comment by joni2back** [comment]
Hi @mrwogu thanks for that crontibution.

What are you meaning with "multiple file managers with different options " ?
Regards.

**Comment by mrwogu** [comment]
@joni2back, with your current version - you have global configuration for whole module.  It means that you can use countless times file manager directives and all of them will have one configuration.
My feature allows to set individual configuration for several file manager's directive.
Ex. you can use 
```
<angular-filemanager config="managerOptions1"></angular-filemanager>
<angular-filemanager config="managerOptions2"></angular-filemanager>
```
It could be helpful if you want use file manager for many servers in your angular application.

**Comment by joni2back** [comment]
Great, and the last doubt..
Where and which scope do you need to set your 
``$scope.managerOptions``

**Comment by mrwogu** [comment]
In controller when you use filemanager directive.

**Comment by joni2back** [comment]
So, how you extend the configuration for each instance without modifying the source code? (because we have a workaround to do that currently)

**Comment by mrwogu** [comment]
@joni2back just check example in my edited readme.md

**Comment by joni2back** [comment]
Hi.. This is interesting, but please we need to find a way to do it wihout modifying the source code of the controller, etc.. just using the config extension.

**Pull request closed without merging**
