### PR TITLE
Slovak translation and new file upload #73

### PR DESCRIPTION
**Pull request by jlamer**
Hey, here is new request with changes from click-changes which could be merged without problems. I also added Slovak translation.

### CODE REVIEW

**Comment by joni2back** [comment]
Hi @jlamer . This PR has changes of your other PR, can you please do a merge request from a clean branch?

Just files  ```src/js/providers/translations.js``` and ```src/templates/navbar.html```

**Comment by jlamer** [comment]
I did this on purpose. I also resolved issues with merge problems and merged my other changes with your click branch.

**Comment by jlamer** [comment]
You can close the old one and just use this.

**Comment by joni2back** [comment]
Merged individually the slovak translations

**Pull request closed without merging**
