### PR TITLE
Better scale displayed file-size by using appropriate unit and support binary prefixes.

### PR DESCRIPTION
**Pull request by fkoester**
And a another suggestion for improvement:

Better scale displayed file-size by using appropriate unit (kB, MB, TB etc).

Also allow to use SI compliant binary prefixes (KiB, MiB, TiB etc) by setting config
parameter:

useBinarySizePrefixes: true

### CODE REVIEW

**Comment by fkoester** [comment]
Example: 
file-size

**Comment by joni2back** [comment]
Hi @fkoester I pushed your pr and added the config param that is missing here.
Also I added this filter to anchor titles that still used sizeKb()

**Comment by fkoester** [comment]
@joni2back Perfect!

**Comment by fkoester** [comment]
Or let's say almost perfect ;-) You have overwritten the `showSizeForDirectories` change of the previous PR:

here is the patch: 

```
diff --git a/src/templates/main-table.html b/src/templates/main-table.html
index 8369834..d4d121c 100644
--- a/src/templates/main-table.html
+++ b/src/templates/main-table.html
@@ -53,7 +53,9 @@
                 </a>
             </td>
             <td class="hidden-xs">
+              <span ng-show="item.model.type !== 'dir' || config.showSizeForDirectories">
                 {{item.model.size | humanReadableFileSize }}
+              </span>
             </td>
             <td class="hidden-sm hidden-xs" ng-hide="config.hideDate">
                 {{item.model.date | formatDate }}
```

**Comment by joni2back** [comment]
done!

**Pull request merged**
