### PR TITLE
Filtering in main-table does not work properly

### PR DESCRIPTION
**Pull request by hmartos**
The filter in main-table was filtering in the hole item object, making some strange behaviours when filtering words like 'dir' or 'false', now it filters only by item.model.name field

### CODE REVIEW

**Comment by joni2back** [comment]
Great !!
To merge this pull request you need to discard the changes to the php folder (bridges/php/php-classic) 
Also, should be great if you compile the javascript with the gulp task (dist/angular-filemanager.min.js)

Example:
```
jonas@:~/www/angular-filemanager$: npm install #(install dependencies to execute gulp)
jonas@:~/www/angular-filemanager$: gulp build  #(generate the js in dist folder)

**Comment by hmartos** [comment]
Ok!, I am going!

**Comment by hmartos** [comment]
I have errors when doing gulp build  "Expected linebreaks to be 'LF' but found 'CRLF'" I think this line break differences between operating systems (I am using Windows). I am very new on this so make me know if there is any other problem. Thank you for your time!

**Comment by joni2back** [comment]
Yes, is the difference in the line break between windows and linux (\r\n vs \n)
Merge was done, I had to fix the php-classic submodule in a new commit. but is ok.
Thanks!!

**Comment by hmartos** [comment]
Thank you @joni2back! Awesome project!

**Comment by joni2back** [comment]
Thank you too.
PD: If you want to collaborate in any other feature addition or bugfix, you are welcome!
(there are a known bug in the sidebar, maybe you are the ideal dev to fix this #63)

**Pull request merged**
