### PR TITLE
Set initial pat service: to open the file browser with any folder

### PR DESCRIPTION
**Pull request by nmeegama**
I wrote a service and a controller for the user to set the initial path in case they do not want to start from root (/)
Set with
<angular-filemanager data-ng-controller="PathCtrl" data-ng-init="setInitPath(['Folder', 'sub_folder'])"></angular-filemanager>

Also fixed a error on the Gulp build process
Changed this line in the cache-templates task

return tplPath + '/' + path.basename(file.history);
to

return tplPath + '/' + path.basename(file.history[0]);

### CODE REVIEW

**Comment by joni2back** [comment]
Hi @nmeegama thanks for your contribution.
How the user can specify the initial path without changing the source code?
I mean, will be good if this can be specified by the configuration extension

**Comment by nmeegama** [comment]
Hi,

Thank you for the feedback. So this is actually a requirement I came
through when using the file manager, Basically what I needed is to open
different folders in my remote file system on different paths ex:

Assume my remote folder structure is as follows


   - Folder1
      - folder11
      - folder12
      - folder13
         - folder131

when the user hits

example.com/path1 -  I want to open folder11
example.com/path2 -  I want to open folder12
example.com/path3 -  I want to open folder131

so the onlyway to do this was to pass something from the directive on the
page unless we add and associated array / json in the config file. But I
though passing the init- path from the directive is the best thing

So now in

   - example.com/path1
   - we can use
      - <angular-filemanager data-ng-controller="PathCtrl"
      data-ng-init="setInitPath([*'Folder1', 'folder11'*
      ])"></angular-filemanager>
      - example.com/path3
   - we can use
      - <angular-filemanager data-ng-controller="PathCtrl"
      data-ng-init="setInitPath([*'Folder1', 'folder13', 'folder131'*
      ])"></angular-filemanager>

This was the nee

If the users just uses


   - <angular-filemanager></angular-filemanager>
   - This will as usual open Folder1 according to the example I have given.


One thing I can do though is add this on the README file but I have added a
comment on the index.html file.


Let me know your thoughts


Thanks
Nirak

**Comment by joni2back** [comment]
Hi @nmeegama would be great replace your controllers by a directive
And also prevent any kind of errors using a default value for the path. 
Example.. ```this.currentPath = initPath || []```

**Comment by joni2back** [comment]
Hi @nmeegama this was implemented in a different way.
You can now set the root folder in config.basePath.

Thanks!!

**Comment by nmeegama** [comment]
Hi @joni2back, sorry got really busy in the office. Nice to hear this. 
Thank you

**Pull request closed without merging**
