### PR TITLE
Allow file download via angular-file-saver

### PR DESCRIPTION
**Pull request by fkoester**
For my use case I implemented a Backend wich uses JWT for authentication/authorization of users. For this to work the client sends a token using the HTTP header "Authorization". This works fine when making Ajax requests (like /list) from the angular app (because I configured an http interceptor which sets this header) but it does not work for downloading files (which is not an ajax request).

As a solution I integrated [angular-file-saver](https://github.com/alferov/angular-file-saver) which downloads the data per Ajax, creates a blob object and then saves the file.

This method is disabled by default but can be enabled using the config param `downloadViaFileSaver`.

### CODE REVIEW

**Comment by joni2back** [comment]
Hi @fkoester thanks for this contribution.
In my last version of Chrome im getting the following error:
```Error: saveAs is not supported. Please include saveAs polyfill```

So, I used this polyfill and works fine https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js
Will be great if we can ensure that the browser support this to prevent this kind of errors, or use this polyfill as a dependency (not the best approach)

It's possible to show any kind of spinner when the request is working? because its very confusing for big files...

Regards!!

**Comment by fkoester** [comment]
Sorry, that was my fault. The polyfils FileSaver.js and Blob.js are downloaded as transitive dependencies by bower, but I forgot to include them in index.html. Should work out-of-the-box now.

The download progress is a good point! This method is currently only working for smaller files, but a progress indicator would still be nice! I tried [angular-loading-bar](http://chieffancypants.github.io/angular-loading-bar/) which should work instantly with all `$http` requests, but somehow it did not. I will try that again later.

**Comment by joni2back** [comment]
I'll be merging your changes on click-changes branch, because API changes here.
If you have some time, check out this branch and let me know if you like and can be used easily.

This is the online link: http://angular-filemanager.zendelsolutions.com/v2/

**Comment by joni2back** [comment]
Hi again @fkoester .
Im thinking if this could be possible without using the dependency, just using saveAs polyfill.
```js
$http.post(fileUrl, { responseType: 'arraybuffer' })
  .success(function(data) {
            var file = new Blob([data]);
            $window.saveAs && saveAs(file, item.model.name);
        });
```

What do you think? Which are the differences?

**Comment by joni2back** [comment]
Take look to 18ee276e5c120258808069a59eac3f150cc631ea, I'm using without the dependency.
What do you think? There are any difference using **angular-file-saver** ?

**Pull request closed without merging**
