### PR TITLE
File upload v2

### PR DESCRIPTION
**Pull request by durasj**
Rewritten file upload using [ng-file-upload](https://github.com/danialfarid/ng-file-upload)

Related to #73

### CODE REVIEW

**Comment by joni2back** [comment]
I will doing some changes in src/js/services/apihandler.js before it be merged

**Comment by RGFnaGFuIEd1bmF5** [comment]
I think you should use ng-flow. It has much more api neither than ng-file-upload. Its allow directory upload for example.

**Comment by durasj** [comment]
Looks interesting, but I think it is doing a little bit more than we need. I took a quick look at quick start and I think it would be harder to implement so it leaves current APIMiddleware etc. in place. And ng-file-upload has 30 open issues while ng-flow 111. So for now I will stick with what I've done.

Btw. you can upload directories if you upload and extract zip.

**Comment by durasj** [comment]
What stops us from merging @joni2back ?

**Pull request merged**
