### PR TITLE
Drop files anywhere to upload

### PR DESCRIPTION
**Pull request by jlamer**
Simple integration of https://github.com/danialfarid/ng-file-upload at user interface.
So far not using Upload functions of module. I have to take better look at bridge and how upload is done at the moment so I won't break backward compatibility.

### CODE REVIEW

**Comment by joni2back** [comment]
Hi @jlamer great contribution!!!
I'll be testing this and merging asap.
Thanks!!

**Comment by jlamer** [comment]
I tried to do everything same way you do. I will be hopefully able to do few more contributions in the near future.

**Comment by joni2back** [comment]
I'll be merging your changes on [click-changes](https://github.com/joni2back/angular-filemanager/tree/click-changes) branch, because API changes here.
So, if you have some time, check out this branch and let me know if you like and can be used easily.

Regards!

**Comment by joni2back** [comment]
http://angular-filemanager.zendelsolutions.com/v2/

**Comment by jlamer** [comment]
So you want me to to close this issue and reopen new one which would be forked from click-changes and merged back to click-changes?

**Comment by jlamer** [comment]
#114 should be used instead ...

**Pull request closed without merging**
