### PR TITLE
Fixes, improvements in php local bridge

### PR DESCRIPTION
**Pull request by durasj**
- file paths are canonical
- system dependant DIRECTORY_SEPARATOR is used
- glob in list action is replaced to prevent issues with special chars like *[]! etc
- uploaded file names are normalized so they contain only ASCII characters
- support for nested directories for compression

### CODE REVIEW

**Comment by elboletaire** [comment]
Will this fix the issue for absolute paths (are not working right now)?

**Comment by durasj** [comment]
Hi @elboletaire, could you please explain? Where do you use absolute paths?

**Comment by elboletaire** [comment]
[I'd like to define the `basePath`](https://github.com/elboletaire/docker-angular-filemanager/blob/master/templates/configuration-php-local.js#L18) as an absolute path, but I can't due to how is initialized the `basePath` in the php-local bridge.

https://github.com/joni2back/angular-filemanager/blob/master/bridges/php-local/index.php#L20
https://github.com/joni2back/angular-filemanager/blob/master/bridges/php-local/LocalBridge/FileManagerApi.php#L22

The `FileManagerApi` is initialized without any param, what causes the `$this->basePath` to be set by default. After that you can't change the `$this->basePath` and everything works taking that `basePath` as the main `basePath`, which forces me to use relative paths instead of absolute ones.

**Comment by elboletaire** [comment]
Sorry about my ignorance, but I discovered this project yesterday and, while searching how to implement this I found, somewhere (I cannot find it right now), that one can use both absolut and relative paths, but from my experience the only available option is the relative path.

Searching it now I've found this issue https://github.com/joni2back/angular-filemanager/issues/129#issuecomment-205046040 where DarkStar1 is setting the path directly in the bridge. Is that the way to proceed?

**Comment by durasj** [comment]
Yes, that's exactly the way to go. The index.php there serves just as an example. You can copy it somewhere else if you wish and modify it to your liking so that it won't get overwritten on updates.

**Comment by elboletaire** [comment]
It would be really nice to have a way to configure this just using the angular configuration.

I'll open a feature request (issue) asking for it then.

**Comment by durasj** [comment]
I am not really a fan of that. Because usually, that would be rather dangerous. It's already dangerous as it is now (since you can define paths with ../ when doing some operations, but which could be worked on), but with the change you proposed, you could set the root to / (root) easily for everything. I absolutely don't recommend using this in env where it could be a problem, but some people still will.

**Comment by elboletaire** [comment]
The path you put there is your responsibility. If you decide to put the root is your own business. I think you should grant the user the ability to put whatever they want in there.

On the other hand, the way is done now confuses me (and probably other people, as this is not documented anywhere), because when you discover this project the only way to configure it, following the documentation, is with the angular configuration array.

Although, after you've been confused you'd probably end doing something like I did, using a relative path, which brings some issues to the app (like allow you to access any of the `..` defined in your route). In my case I access `../../../files`, which allows the user to navigate to `..`, `../..` and `../../..`. The first one contains the bridges folder, the second one the entire app and, finally, you can access the parent `www` folder, which is not accessible by the apache web server directly.

So, IMHO, I think both cases are dangerous, everything depends on how do you use it. And giving the users the ability to configure the absolute path directly from angular would ease a lot the initialization/configuration of this file manager.

**Comment by elboletaire** [comment]
Ok, thinking better on it now, I see where the problem would be... we're using javascript, and javascript can be modified directly on the client. Oh god! I've been an idiot xD

BTW, I still think it would be awesome to have an easier way to configure this...

**Comment by durasj** [comment]
Agreed that it'll be easier to configure etc. but the danger coming from the base path being set on the client side is something that can be hard to work around... Yeah, what you wrote basically :) And since we would have to have some API endpoint on the bridges for this too, you could, as an attacker, set it to anything you like. In case you wouldn't have the filesystem set correctly, that would be a very weak point not only for the file manager itself.

PRs are welcome. I see you know a thing or two, so I'm sure you can come up with something better ;) For example having .gitignored config.json and adding additional security check of the path used in the actions would be super welcome.

**Pull request merged**
