### PR TITLE
Embedding angular-filemanager

### PR DESCRIPTION
**Pull request by fkoester**
Do not always use full viewport to allow embedding angular-filemanager as a widget into other webapps.

For example like that:

HTML snippet:
```
<body>
	<header>
		<nav class="navbar" style="margin-bottom: 0;" role="navigation">
			<div>
				<a class="navbar-brand" href="/" style="padding-top: 0;">
					<h1>Fancy webapp</h1>
					<h2>For secure fileexchange</h2>
				</a>
				<div class="btn-group navbar-right navbar-button" data-ng-cloak>
					<ul class="nav navbar-nav" data-ng-cloak>
						<li><a href="/users">Manage users</a></li>
						<li><a href="/logout">Logout</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</header>

	<angular-filemanager></angular-filemanager>
</body>
```

CSS:
```
header .navbar {
  height: 80px;
}

angular-filemanager > div {
  overflow-y: hidden;
  height: calc(100vh - 80px);
}
```

angular-filemanager-embeddable

### CODE REVIEW

**Comment by fkoester** [comment]
Using it standalone with angular-filemanger's index.html should still produce the same output, btw.

**Comment by joni2back** [comment]
Hi @fkoester , there are a problem with chrome (in my case) with items container.
angular filemanager

I would like to embed  ***<angular-filemanager>*** in a div for example:

```html
<div style="width:800;height:600;border:1px solid red">
  <angular-filemanager></angular-filemanager>
</div>

**Comment by fkoester** [comment]
I tested with Chrome but obviously not good enough :-D I will look into this again.

**Comment by fkoester** [comment]
Strange, your example is working for me with Chrome:

angular-filemanager-embeddable-chrome

I will prepare a full example for analysing this.

**Comment by fkoester** [comment]
I just created a reproducable setup to investigate the issue you showed above. Turns out I am now having the same problem, even with Firefox. So at least the problems seems to be reproducable. I will try to find the reason now.

**Comment by joni2back** [comment]
Im thinking what could happend in mobile viewport changing these styles :thought_balloon:

**Comment by fkoester** [comment]
Should be fixed now, I forgot to commit the changes in main.html.

You can access my test setup here: http://134.119.46.162:8080/

The source code for this demo setup is here: https://github.com/fkoester/angular-filemanager-demo

**Comment by fkoester** [comment]
> Im thinking what could happend in mobile viewport changing these styles :thought_balloon:

I tested it with mobile screen dimensions and it is still responsive and working just fine. Although the behavior changed a little bit:

With the original CSS the menu (navbar) overlaps the main view when pressing the "burger menu" button:

angular-filemanager-mobile-chrome

With my modified CSS the main view scrolls down and is fully visible:

angular-filemanager-mobile-chrome-embeddable

I have to say I like my version better, because the whole content is always visible.

**Comment by fkoester** [comment]
I updated the demo to show an example on how to embed it into your page:

angular-filemanager-embeddable-example

**Comment by joni2back** [comment]
Hi again @fkoester 
I tested your changes and working fine now.
But i also have tested others situations and here are the problems
--------------


sidebar is not fixed now, so the background of this area is cropped

-----------


if the container div of <angular-filemanager> has defined height, this is overlapped (i tested with overflow:hidden the parent div but the internal scrollbars seems weird when comming down)

-----------


the mobile view is affected with the container styles.. maybe this is obvious but i dont know...

**Comment by fkoester** [comment]
@joni2back Can you provide example code for this issues?

**Comment by joni2back** [comment]
I remember I used..
```html
<div style="width:700px;height:600px;margin:10px auto;border:1px solid red">

**Comment by joni2back** [comment]
beyond the weird cases problems, im very interested to have this merge request

**Comment by fkoester** [comment]
I will look into that I think tomorrow.

**Comment by fkoester** [comment]
I managed to reproduce the two latter issues you outlined above and extended my test setup at http://134.119.46.162:8080/ to include your cases. I could not reproduce the one with the cropped sidebar background, though. Can you still reproduce it?

So, there are at least three issues to fix:

1.) Sidebar background cropped (which I cannot reproduce yet).
2.) Height of both sidebar and file list exceed the container's height if that is set to some fixed value.
3.) View is not fully responsive if angular-filemanager does not use the full screen width (Because the current media queries apply to the screen width and not only a-fm's width)

I will have some time tomorrow to fix some of those issues.

**Comment by joni2back** [comment]
Done bro !! :sunglasses:

**Comment by fkoester** [comment]
Thanks for merging :thumbsup:

For the remaining issues, i create a new pull request.

**Comment by jlamer** [comment]
Looks great!

**Pull request merged**
